feeds:
  - name: Bad Astronomy
    url: http://www.slate.com/blogs/bad_astronomy.fulltext.all.rss
  - name: Boing Boing
    url: http://boingboing.net/feed
  - name: Whatever
    url: http://whatever.scalzi.com/feed
  - name: xkcd
    url: http://xkcd.com/rss.xml

keys:
  open: ' '
  prev_item: K
  next_item: J
  prev_feed: H
  next_feed: L
  scroll_up: KEY_UP
  scroll_down: KEY_DOWN
  toggle_read: R
  toggle_star: S
  open_in_browser: O
  quit: Q

database: ~/.tread.db
parser: html2text
retries: 10
timeout: 10
refresh: 10
scroll_lines: 5
ascii_images: true
image_blocks: true
buffer_lines: 1000
unread_count: true
